services:
  app:
    image: t2m:latest
    container_name: streamlit_app
    env_file:
      - .env
    environment:
      - PORT=7860
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped
    expose:
      - "7860"            # chỉ lộ port trong mạng nội bộ Docker
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:7860/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Nếu app cần ghi file ngoài container, map volume ở đây
    volumes:
      - ./data:/app/output

  caddy:
    image: caddy:2
    container_name: caddy_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
