[project]
name = "theory2video"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "manim>=0.19.0",
    "streamlit>=1.49.1",
]
